spring:
  application:
    # 服务名
    name: exam
  profiles:
    # 使用那个配置文件
    active: dev

ai:
  doubao:
    api-key: xxxxxxxxxxxxxxxxx
    api-url: https://ark.cn-beijing.volces.com/api/v3/chat/completions
    model: doubao-seed-1-6-251015
    timeout: 60