spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_exam?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 【请填写本地数据库密码】
  redis:
    host: localhost
    port: 6379
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: cn.org.alan.exam.model.entity
